min-pay-per-km: 8
max-pay-per-km: 25
max-trip-distance-kms: 30
max-trip-time-mins: 120
pickup-canceled:
  too-big:
    rider-paid: 10%
    customer-pays: 10%
  restricted-item:
    rider-paid: 20%
    customer-pays: 20%
  insufficient-packaging:
    rider-paid: 10%
    customer-pays: 10%
  drop-to-far:
    rider-paid: 10%
    customer-pays: 10%
  pickup-location-embargo:
    rider-paid: 10%
    customer-pays: 10%
  rider-change-of-heart:
    rider-paid: -20%
    customer-pays: 0%
  customer-change-of-heart:
    rider-paid: 20%
    customer-pays: 20%
  rider-not-reachable:
    rider-paid: -20%
    customer-pays: 0%
  pickup-person-not-reachable:
    rider-paid: 20%
    customer-pays: 20%
  other:
    rider-paid: 0%
    customer-pays: 0%
returned:
  rider-change-of-heart:
    rider-paid: -50%
    customer-pays: 0%
  customer-change-of-heart:
    rider-paid: 100%
    customer-pays: 100%
  too-big:
    rider-paid: 0%
    customer-pays: 0%
  restricted-item:
    rider-paid: 0%
    customer-pays: 0%
  insufficient-packaging:
    rider-paid: 0%
    customer-pays: 0%
  drop-to-far:
    rider-paid: -20%
    customer-pays: 0%
  insufficient-fuel:
    rider-paid: -20%
    customer-pays: 0%
  recipient-not-available:
    rider-paid: 150%
    customer-pays: 150%
  recipient-location-embargo:
    rider-paid: 150%
    customer-pays: 150%
  other:
    rider-paid: 0%
    customer-pays: 0%
drop-canceled:
  package-lost-in-transit:
    rider-paid: -200%
    customer-pays: -200%
  rider-accident:
    rider-paid: -200%
    customer-pays: -200%
  physical-damage:
    rider-paid: -200%
    customer-pays: -200%
  contents-spilled:
    rider-paid: -200%
    customer-pays: -200%
  water-damage:
    rider-paid: -200%
    customer-pays: -200%
  customer-change-of-heart:
    rider-paid: 100%
    customer-pays: 100%
  rider-not-reachable:
    rider-paid: -200%
    customer-pays: -200%
  other:
    rider-paid: -200%
    customer-pays: -200%
delivered: 
  physical-damage:
    rider-paid: 80%
    customer-pays: 80%
  contents-spilled:
    rider-paid: 80%
    customer-pays: 80%
  water-damage:
    rider-paid: 80%
    customer-pays: 80%
  other: 
    rider: 100%
    customer: 100%