min_pay_per_km: 8
max_pay_per_km: 25
pickup_canceled:
  too_big:
    rider_paid: 10%
    customer_pays: 10%
  restricted_item:
    rider_paid: 20%
    customer_pays: 20%
  insufficient_packaging:
    rider_paid: 10%
    customer_pays: 10%
  drop_to_far:
    rider_paid: 10%
    customer_pays: 10%
  pickup_location_embargo:
    rider_paid: 10%
    customer_pays: 10%
  rider_change_of_heart:
    rider_paid: _20%
    customer_pays: 0%
  customer_change_of_heart:
    rider_paid: 20%
    customer_pays: 20%
  rider_not_reachable:
    rider_paid: _20%
    customer_pays: 0%
  pickup_person_not_reachable:
    rider_paid: 20%
    customer_pays: 20%
  other:
    rider_paid: 0%
    customer_pays: 0%
returned:
  rider_change_of_heart:
    rider_paid: _50%
    customer_pays: 0%
  customer_change_of_heart:
    rider_paid: 100%
    customer_pays: 100%
  too_big:
    rider_paid: 0%
    customer_pays: 0%
  restricted_item:
    rider_paid: 0%
    customer_pays: 0%
  insufficient_packaging:
    rider_paid: 0%
    customer_pays: 0%
  drop_to_far:
    rider_paid: _20%
    customer_pays: 0%
  insufficient_fuel:
    rider_paid: _20%
    customer_pays: 0%
  recipient_not_available:
    rider_paid: 150%
    customer_pays: 150%
  recipient_location_embargo:
    rider_paid: 150%
    customer_pays: 150%
  other:
    rider_paid: 0%
    customer_pays: 0%
drop_canceled:
  package_lost_in_transit:
    rider_paid: _200%
    customer_pays: _200%
  rider_accident:
    rider_paid: _200%
    customer_pays: _200%
  physical_damage:
    rider_paid: _200%
    customer_pays: _200%
  contents_spilled:
    rider_paid: _200%
    customer_pays: _200%
  water_damage:
    rider_paid: _200%
    customer_pays: _200%
  customer_change_of_heart:
    rider_paid: 100%
    customer_pays: 100%
  rider_not_reachable:
    rider_paid: _200%
    customer_pays: _200%
  other:
    rider_paid: _200%
    customer_pays: _200%
delivered: 
  physical_damage:
    rider_paid: 80%
    customer_pays: 80%
  contents_spilled:
    rider_paid: 80%
    customer_pays: 80%
  water_damage:
    rider_paid: 80%
    customer_pays: 80%
  other: 
    rider: 100%
    customer: 100%