export const SCM_DB_FETCH = 'http://localhost:8080/v1/db/fetch'
export const SCM_DB_INSERT = 'http://localhost:8080/v1/db/insert'
export const SCM_DB_DELETE = 'http://localhost:8080/v1/db/delete'
export const SCM_DB_UPDATE = 'http://localhost:8080/v1/db/update'
export const SLACK_MESSAGING = 'https://hooks.slack.com/services/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'
export const SYS_CONFIG = 'http://localhost:8080/v1/config/sysconfig'
export const COMPENSATION_CONFIG = 'http://localhost:8080/v1/config/compensation'
export const CREATE_BOOKING = 'http://localhost:8080/v1/bookings/create'