export const SCM_DB_FETCH = 'http://localhost:8080/v1/db/fetch'
export const SCM_DB_INSERT = 'http://localhost:8080/v1/db/insert'
export const SCM_DB_DELETE = 'http://localhost:8080/v1/db/delete'
export const SCM_DB_UPDATE = 'http://localhost:8080/v1/db/update'
export const UNITY_ACCEPT_BOOKING = 'http://localhost:8000/v1/rider/accept-booking'
export const SLACK_MESSAGING = 'https://hooks.slack.com/services/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'